export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const REMOVE_CUSTOMER = "REMOVE_CUSTOMER";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";

export const FETCH_REPORTS = "FETCH_REPORTS";
export const ADD_REPORT = "ADD_REPORT";

export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";

export const SELECTED_VIEW = "SELECTED_VIEW";
export const SHOW_ADD_CUSTOMER = "SHOW_ADD_CUSTOMER";
export const SHOW_ADD_EMPLOYEE = "SHOW_ADD_EMPLOYEE";
export const SHOW_ADD_REPORT = "SHOW_ADD_REPORT";
export const SHOW_LIST = "SHOW_LIST";

export const FETCH_PERSON = "FETCH_PERSON";
export const UPDATE_PERSON = "UPDATE_PERSON";
export const ADD_PERSON = "ADD_PERSON";

export const FETCH_COMPANY = "FETCH_COMPANY";

export const SET_THEME = "SET_THEME";
export const ENABLE_THEME = "ENABLE_THEME";
export const SET_THEME_NUMBER = "SET_THEME_NUMBER";
