export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const ADD_CUSTOMER_TO_LIST = 'ADD_CUSTOMER_TO_LIST';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';