export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const REMOVE_CUSTOMER = "REMOVE_CUSTOMER";
export const FETCH_REPORTS = "FETCH_REPORTS";
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
